[theme]
base = "light"

primaryColor = "#D97706"
backgroundColor = "#F5F3EF"
secondaryBackgroundColor = "#E7E5E4"
textColor = "#292524"

baseRadius = "medium"
buttonRadius = "medium"
borderColor = "#C8C2BA"
showWidgetBorder = true
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#292524"
secondaryBackgroundColor = "#44403C"
textColor = "#FAFAF9"
primaryColor = "#F59E0B"